"""
Shared fixtures for all tests.
"""
import os
import shutil
import sys
import warnings
from pathlib import Path

import pytest

# 注意：basetemp 落点由 backend/pytest.ini 的 addopts 控制（--basetemp=.pytest-basetemp），
# 以避免打包机器遗留的受限 ACL 目录（%TEMP%\pytest-of-<user> 等）破坏 tmp_path fixture。

# Configure an isolated runtime before test modules import ``app``.  The test
# suite never writes the user's database/uploads and never spends a real key.
BACKEND_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BACKEND_DIR.parent
TEST_RUNTIME = BACKEND_DIR / ".pytest-runtime"
if TEST_RUNTIME.exists():
    try:
        shutil.rmtree(TEST_RUNTIME)
    except OSError as exc:
        # Cleanup failures must stay visible instead of silently reusing stale files.
        warnings.warn(
            f"cannot clean previous test runtime {TEST_RUNTIME}: {exc}; "
            "stale files may remain",
            RuntimeWarning,
            stacklevel=1,
        )
(TEST_RUNTIME / "uploads").mkdir(parents=True, exist_ok=True)
(TEST_RUNTIME / "outputs").mkdir(parents=True, exist_ok=True)

os.environ["DATABASE_URL"] = f"sqlite:///{(TEST_RUNTIME / 'review.db').as_posix()}"
os.environ["UPLOAD_DIR"] = str(TEST_RUNTIME / "uploads")
os.environ["OUTPUT_DIR"] = str(TEST_RUNTIME / "outputs")
os.environ["RULES_DIR"] = str(PROJECT_ROOT / "rules")
os.environ["LLM_API_KEY"] = ""
os.environ["ACCESS_TOKEN"] = ""
os.environ["ADMIN_TOKEN"] = ""
os.environ["AUTH_REQUIRED"] = "false"
os.environ["DEBUG"] = "false"
os.environ["LOG_FILE"] = ""
# 测试环境离线且确定：默认不尝试 OCR（本机无 tesseract）。需要验证 OCR 分支的
# 测试请显式 monkeypatch settings.OCR_ENABLED 或 fitz 接口，而不是依赖真实运行时。
os.environ["OCR_ENABLED"] = "false"
# R07：生产默认不创建演示账号，测试**显式**开启演示账号（并关闭强制改密），
# 而不是依赖不安全的默认值；需要验证生产初始化行为的测试自行 monkeypatch 这两个开关。
os.environ["AUTH_CREATE_DEMO_USERS"] = "true"
os.environ["AUTH_FORCE_DEMO_PASSWORD_CHANGE"] = "false"
# R08：材料外发默认关闭；需要验证"允许外发"路径的测试自行显式打开（配合 mock）。
os.environ["AI_EGRESS_ENABLED"] = "false"
# 账号维度登录限速：测试会话会反复登录同一演示账号，默认 20/分钟 会造成
# 跨测试的 429 抖动；限速逻辑本身仍由 monkeypatch 到 2 的专门用例覆盖。
os.environ["LOGIN_USER_RATE_LIMIT_PER_MINUTE"] = "1000"

sys.path.insert(0, str(BACKEND_DIR))


@pytest.fixture(scope="session", autouse=True)
def _start_backend_services():
    """会话级显式启动后端服务（建表、默认账号、规则种子、执行器）。

    导入 routes 不启动服务，TestClient 不用 ``with`` 也不触发 lifespan，故设此入口。"""
    from app.api import routes

    routes.startup_services()
    yield


def pytest_sessionfinish(session, exitstatus):
    try:
        from app.api import routes
        routes.shutdown_services()
    except Exception as exc:  # keep cleanup failures visible
        warnings.warn(f"shutdown_services failed: {exc}", RuntimeWarning, stacklevel=1)
    try:
        from app.models.base import engine
        engine.dispose()
    except Exception as exc:
        warnings.warn(f"engine.dispose failed: {exc}", RuntimeWarning, stacklevel=1)
    try:
        shutil.rmtree(TEST_RUNTIME)
    except OSError as exc:
        warnings.warn(
            f"test runtime cleanup failed, leftovers at {TEST_RUNTIME}: {exc}",
            RuntimeWarning,
            stacklevel=1,
        )
    basetemp_dir = BACKEND_DIR / ".pytest-basetemp"
    if basetemp_dir.exists():
        try:
            shutil.rmtree(basetemp_dir)
        except OSError as exc:
            warnings.warn(
                f"basetemp cleanup failed, leftovers at {basetemp_dir}: {exc}",
                RuntimeWarning,
                stacklevel=1,
            )


@pytest.fixture
def sample_docx_path() -> Path:
    """Path to the sample proposal DOCX generated by eval/generate_sample_docx.py."""
    p = Path(__file__).resolve().parent.parent.parent / "eval" / "samples" / "sample_proposal.docx"
    if not p.exists():
        pytest.skip("sample_proposal.docx not found — run eval/generate_sample_docx.py first")
    return p


@pytest.fixture
def eval_dir() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "eval"
